/* Casos originales de preparación. La primera opción es la clave; app.js baraja su posición.
   Las fuentes respaldan el principio explicado, no un examen ni un procedimiento de Hubbard. */
(() => {
  const sources = {
    eye: ['CCOHS · Protección de ojos y cara', 'https://www.ccohs.ca/oshanswers/prevention/ppe/glasses.html'],
    hearing: ['CCOHS · Protectores auditivos', 'https://www.ccohs.ca/oshanswers/prevention/ppe/ear_prot.html'],
    retrieval: ['Boart Longyear · Componentes del sistema wireline', 'https://www.boartlongyear.com/fr/insite/the-boart-longyear-genuine-q-wireline-system/'],
    fluids: ['Boart Longyear · Fluidos, preparación y trabajo subterráneo', 'https://www.boartlongyear.com/insite/exclusive-interview-with-chris-hopkins-underground-operations-boart-longyear-australia/'],
    rig: ['Boart Longyear · Equipo LF90D', 'https://www.boartlongyear.com/product/lf90d/'],
    competence: ['Registro oficial australiano · Asistir perforación diamantina (RIINHB208E)', 'https://training.gov.au/TrainingComponentFiles/RII/RIINHB208E_R1.pdf'],
    career: ['Boart Longyear · Vida y tareas de una cuadrilla', 'https://www.boartlongyear.com/insite/a-career-like-no-other-are-you-up-for-the-challenge/'],
    surfaceJob: ['Boart Longyear · Funciones de ayudante en superficie (Australia)', 'https://careers.boartlongyear.com/jobs/driller-assistant-surface-coring-perth-wa-au-56'],
    tools: ['CCOHS · Herramientas manuales', 'https://www.ccohs.ca/oshanswers/safety_haz/hand_tools/general.html'],
    electric: ['CCOHS · Herramientas eléctricas portátiles', 'https://www.ccohs.ca/oshanswers/safety_haz/power_tools/saf_elec.html'],
    handling: ['CCOHS · Factores del manejo manual de cargas', 'https://www.ccohs.ca/oshanswers/ergonomics/mmh/mmhintro.html'],
    sling: ['CCOHS · Eslingas textiles', 'https://www.ccohs.ca/oshanswers/safety_haz/materials_handling/syn_slng.html'],
    labels: ['CCOHS · Etiquetas de productos químicos (WHMIS/GHS)', 'https://www.ccohs.ca/oshanswers/chemicals/whmis_ghs/labels.html'],
    spill: ['CCOHS · Respuesta a derrames químicos', 'https://www.ccohs.ca/oshanswers/chemicals/spill-response-chemicals.html'],
    respirator: ['CCOHS · Selección de respiradores', 'https://www.ccohs.ca/oshanswers/prevention/ppe/respslct.html'],
    silica: ['OSHA · Sílice cristalina respirable', 'https://www.osha.gov/silica-crystalline'],
    emergency: ['CCOHS · Planificación de emergencias', 'https://www.ccohs.ca/oshanswers/hsprograms/planning.html'],
    fire: ['CCOHS · Extintores portátiles', 'https://www.ccohs.ca/oshanswers/safety_haz/fire_extinguishers.html'],
    confined: ['CCOHS · Reconocer espacios confinados', 'https://www.ccohs.ca/oshanswers/hsprograms/confinedspace/confinedspace_intro.html'],
    rescue: ['CCOHS · Programa y rescate en espacios confinados', 'https://www.ccohs.ca/oshanswers/hsprograms/confinedspace/confinedspace_program.html'],
    heat: ['CCOHS · Evaluación y control del calor', 'https://www.ccohs.ca/oshanswers/phys_agents/heat/heat_control.html'],
    lightning: ['NOAA/NWS · Tormentas eléctricas en el trabajo', 'https://www.weather.gov/safety/lightning-job'],
    fatigue: ['CCOHS · Fatiga en el trabajo', 'https://www.ccohs.ca/products/posters/longdesc/fatigue.html'],
    alone: ['CCOHS · Trabajo aislado y comunicación', 'https://www.ccohs.ca/oshanswers/hsprograms/alone/workingalone.html'],
    traffic: ['CCOHS · Trabajar cerca de maquinaria pesada', 'https://www.ccohs.ca/oshanswers/safety_haz/working-safety-around-heavy-equipment.html'],
    chain: ['CCOHS · Eslingas de cadena', 'https://www.ccohs.ca/oshanswers/safety_haz/materials_handling/sling_c.html'],
    dci: ['Boart Longyear · Interfaz DCi y video del fabricante', 'https://www.boartlongyear.com/product/dci/'],
    loader: ['Boart Longyear · LF160 y cargador FL262, con video', 'https://www.boartlongyear.com/product/lf160/'],
    ecuador: ['Ministerio del Trabajo de Ecuador · Normativa, formatos y guías', 'https://www.trabajo.gob.ec/normativa-legal-programas-formatos-y-guias/']
  };
  const cats = ['Turno y campo', 'Herramientas y cargas', 'Químicos y ambiente', 'Emergencias', 'Clima, fatiga y aislamiento'];
  const bank = [];
  const add = (id,cat,src,q,a,e,critical=false) => bank.push({id,cat,src,q,a,e,critical});

  // Seguridad: selección y uso del EPP, sin trasladar límites legales extranjeros.
  add('s15',0,'eye','La tarea puede producir salpicaduras. ¿Cómo eliges la protección ocular?', ['Según el peligro y las indicaciones de la tarea.','Por el color de la montura.','Cualquier lente de sol sirve.','Solo por su precio.'], 'Las protecciones para impacto y salpicaduras tienen prestaciones distintas. Comprueba su uso previsto.');
  add('s16',0,'eye','¿Por qué unos lentes comunes no demuestran protección para el trabajo?', ['No acreditan las prestaciones de una protección de seguridad.','Porque todos los lentes transparentes son frágiles.','Porque solo se permiten lentes oscuros.','Porque el casco ya protege los ojos.'], 'La protección de seguridad tiene diseño y prestaciones específicos para los peligros de la tarea.');
  add('s17',0,'eye','Ves polvo y partículas proyectadas en una tarea. ¿Qué debe evaluar la cuadrilla?', ['La exposición ocular y los controles adecuados.','Solo si los ojos ya duelen.','Únicamente la velocidad de producción.','El color del polvo para escoger lentes.'], 'Las partículas y el polvo pueden lesionar los ojos. La selección se basa en la evaluación de peligros.');
  add('s18',0,'eye','La protección ocular te queda suelta y dificulta ver. ¿Qué haces?', ['Pido revisar el ajuste antes de la tarea expuesta.','La retiro mientras trabajo.','La sustituyo por lentes de lectura.','Me acerco más a las piezas en movimiento.'], 'La protección debe ajustarse correctamente y mantenerse en condiciones que permitan ver.');
  add('s19',0,'hearing','¿Unos auriculares para música sustituyen a los protectores auditivos?', ['No; necesito protección seleccionada para el ruido de la tarea.','Sí, si subo mucho el volumen.','Sí, si tienen almohadillas.','Solo si escucho música tranquila.'], 'Los auriculares de música no sustituyen la protección auditiva requerida.');
  add('s20',0,'hearing','Un protector auditivo mal colocado, ¿protege igual?', ['No; el ajuste influye mucho en su eficacia.','Sí, basta con llevarlo en la mano.','Sí, si es nuevo.','Sí, si el ruido es constante.'], 'Necesitas formación y ajuste correcto; llevar el protector de forma intermitente reduce su eficacia.');
  add('s21',0,'hearing','Las orejeras interfieren con el otro EPP. ¿Qué hay que revisar?', ['La compatibilidad y el ajuste del conjunto.','Qué EPP puedo quitar sin avisar.','Cómo doblar las orejeras permanentemente.','Si puedo usar algodón en lugar de protección.'], 'La selección debe contemplar el resto del EPP y las necesidades de comunicación.');
  add('s22',0,'hearing','¿Cuál es una medida útil frente al ruido, además de la protección personal?', ['Reducir el ruido en su fuente mediante controles adecuados.','Gritar más fuerte durante todo el turno.','Taparse los oídos solo al pasar el jefe.','Acercarse a la máquina para escuchar mejor.'], 'Controlar la fuente es una medida prioritaria para prevenir daños auditivos.');

  // Comprensión del equipo; no son instrucciones de operación.
  add('p9',1,'retrieval','En un sistema wireline, ¿qué componente recibe el testigo?', ['El tubo interior.','El casco.','El tanque de combustible.','El filtro de aire del motor.'], 'El tubo interior recibe la muestra; se aloja en el conjunto de perforación.');
  add('p10',1,'retrieval','¿Qué permite recuperar el conjunto del tubo interior en wireline?', ['Un overshot conectado al cable.','Una eslinga atada al testigo dentro del pozo.','Un imán colocado en la caja.','Un casco con visor.'], 'El overshot engancha el conjunto de cabeza para recuperar el tubo interior mediante cable y winche.');
  add('p11',1,'retrieval','¿Para qué sirve el mecanismo de retención del conjunto de cabeza?', ['Mantener el tubo interior en posición durante la toma de muestra.','Pesar las cajas.','Señalar la ruta de evacuación.','Enfriar el motor.'], 'El mecanismo retiene el tubo y permite liberarlo para su recuperación; su estado requiere revisión competente.');
  add('p12',1,'retrieval','¿Tubo interior y sarta de barras son lo mismo?', ['No: son componentes distintos del sistema.','Sí, ambos nombres significan la caja de muestras.','Sí, y ambos son el cable.','Solo son distintos cuando llueve.'], 'En wireline, el tubo receptor es independiente de la sarta; reconocerlos evita pedir una pieza equivocada.');
  add('p13',1,'fluids','¿Qué función pueden cumplir los fluidos de perforación?', ['Ayudar a retirar recortes y acondicionar el pozo.','Convertir cualquier roca en mineral valioso.','Eliminar todas las guardas.','Sustituir al perforista.'], 'Los fluidos ayudan al transporte de recortes y al acondicionamiento del pozo según la formación.');
  add('p14',1,'fluids','¿Más aditivo siempre significa mejor perforación?', ['No; el uso debe seguir las indicaciones del fabricante y de la tarea.','Sí, se duplica todo sin consultar.','Sí, si la roca es oscura.','Solo depende del tamaño del balde.'], 'El exceso no garantiza un mejor resultado y puede generar desperdicio; evita improvisar la dosificación.');
  add('p15',1,'fluids','¿Por qué importa preparar correctamente herramientas y materiales antes de empezar?', ['Reduce improvisaciones y errores por apuro.','Permite saltarse la reunión previa.','Hace innecesario comunicar los riesgos.','Garantiza que nunca habrá fallas.'], 'La preparación y la comunicación son parte del trabajo seguro; no eliminan la necesidad de vigilar los cambios.');
  add('p16',1,'fluids','Si cambian las condiciones de la formación, ¿puedes aplicar por tu cuenta una receta anterior?', ['No; el responsable debe evaluar la respuesta adecuada.','Sí, todas las formaciones reaccionan igual.','Sí, basta con mezclar más rápido.','Sí, si la receta salió bien una vez.'], 'La estabilidad y el comportamiento del pozo varían. Las decisiones técnicas corresponden al personal competente.');
  add('p17',1,'rig','La ficha del LF90D menciona una barrera de rotación. ¿Qué debes aprender de eso?', ['Las partes giratorias requieren protecciones y reglas específicas del equipo.','Todas las perforadoras tienen la misma barrera.','La barrera permite tocar barras girando.','Hubbard necesariamente usa este modelo.'], 'Es una característica de ese modelo. Reconocer una protección no autoriza a intervenir la máquina.',true);
  add('p18',1,'rig','¿Para qué sirve consultar la ficha del modelo real de perforadora?', ['Para conocer su configuración y características específicas.','Para copiar cualquier ajuste de otra máquina.','Para sustituir la inducción de campo.','Para demostrar experiencia que no tengo.'], 'Las características publicadas pertenecen al modelo indicado; no las generalices a todos los equipos.');
  add('p19',1,'rig','¿Una ficha comercial basta para aprender a operar una perforadora?', ['No; hacen falta capacitación, autorización y el procedimiento del equipo.','Sí, si memorizo la potencia del motor.','Sí, si reconozco su marca.','Sí, si vi una foto del mástil.'], 'Una ficha describe prestaciones. La operación requiere instrucciones y formación específicas.');
  add('p20',1,'rig','La ficha ofrece montaje sobre camión u orugas. ¿Qué significa?', ['Existen configuraciones de transporte diferentes para ese equipo.','El ayudante puede conducir sin autorización.','Todas las máquinas se trasladan del mismo modo.','El terreno no importa para el traslado.'], 'El LF90D admite configuraciones distintas. El traslado requiere planificación acorde al equipo y al sitio.');

  // Matemáticas propias: datos ficticios, nunca dosis ni límites operativos.
  add('c9',2,'own','Una caja contiene 1,5 m de muestra en cada una de 4 filas llenas. ¿Cuántos metros hay?', ['6 m.','4,5 m.','5,5 m.','8 m.'], '1,5 × 4 = 6 m. Es un ejercicio de longitud; no define el tamaño real de las cajas.');
  add('c10',2,'own','En este ejercicio se recuperan 2,4 m de un avance de 3 m. ¿Cuál es la recuperación?', ['80 %.','60 %.','125 %.','24 %.'], 'Recuperación = longitud recuperada ÷ avance × 100. 2,4 ÷ 3 × 100 = 80 %.');
  add('c11',2,'own','El intervalo empieza en 12,5 m y termina en 15,5 m. ¿Cuál es su longitud?', ['3 m.','28 m.','2 m.','3,5 m.'], '15,5 − 12,5 = 3 m. Anota las unidades junto al resultado.');
  add('c12',2,'own','Hay 8 barras de 3 m en un inventario ficticio. ¿Qué longitud suman?', ['24 m.','11 m.','18 m.','32 m.'], '8 × 3 = 24 m de barras. Esa suma por sí sola no certifica la profundidad de un pozo real.');
  add('c13',2,'own','Un registro suma 6 intervalos iguales de 0,5 m. ¿Cuál es el total?', ['3 m.','6,5 m.','0,3 m.','12 m.'], '6 × 0,5 = 3 m.');
  add('c14',2,'own','¿Cuántos centímetros son 0,75 m?', ['75 cm.','7,5 cm.','750 cm.','0,75 cm.'], '1 m = 100 cm; 0,75 × 100 = 75 cm.');
  add('c15',2,'own','¿Cuántos milímetros son 12 cm?', ['120 mm.','1,2 mm.','12 mm.','1200 mm.'], '1 cm = 10 mm; 12 × 10 = 120 mm.');
  add('c16',2,'own','¿Cuántos litros son 2500 mL?', ['2,5 L.','25 L.','0,25 L.','250 L.'], '1000 mL = 1 L; 2500 ÷ 1000 = 2,5 L.');
  add('c17',2,'own','Tienes 18 cajas y se retiran 7. ¿Cuántas quedan?', ['11.','25.','10.','9.'], '18 − 7 = 11 cajas.');
  add('c18',2,'own','Necesitas 5 paquetes de 12 etiquetas. ¿Cuántas etiquetas son?', ['60.','17.','50.','72.'], '5 × 12 = 60 etiquetas.');
  add('c19',2,'own','Se usan 15 de 60 etiquetas. ¿Qué porcentaje se usó?', ['25 %.','15 %.','40 %.','75 %.'], '15 ÷ 60 × 100 = 25 %.');
  add('c20',2,'own','El ejercicio inicia a las 07:40 y termina a las 09:10. ¿Cuánto dura?', ['1 h 30 min.','1 h 70 min.','2 h 10 min.','50 min.'], 'De 07:40 a 08:40 pasa una hora; hasta 09:10, otros 30 minutos.');
  add('c21',2,'own','¿Cuántos minutos equivalen a 2,5 horas?', ['150 min.','125 min.','250 min.','120 min.'], '2,5 × 60 = 150 minutos. Media hora son 30 minutos, no 50.');
  add('c22',2,'own','En un inventario hay 120 L y se registran 35 L y 20 L de salida. ¿Qué saldo calculas?', ['65 L.','85 L.','75 L.','175 L.'], '120 − 35 − 20 = 65 L. El saldo calculado debe contrastarse con el inventario real.');
  add('c23',2,'own','Un pedido requiere 48 piezas y tienes 39. ¿Cuántas faltan?', ['9.','87.','11.','8.'], '48 − 39 = 9 piezas.');
  add('c24',2,'own','Una medición pasa de 18,2 m a 20,7 m. ¿Cuánto aumentó?', ['2,5 m.','38,9 m.','2,7 m.','1,5 m.'], '20,7 − 18,2 = 2,5 m.');
  add('c25',2,'own','En el ejercicio, tres tramos miden 1,2 m, 0,8 m y 1,5 m. ¿Qué suman?', ['3,5 m.','2,5 m.','3 m.','4,5 m.'], '1,2 + 0,8 + 1,5 = 3,5 m.');
  add('c26',2,'own','Se recuperan 1,5 m de un intervalo de 2 m. ¿Cuál es la recuperación?', ['75 %.','50 %.','133 %.','15 %.'], '1,5 ÷ 2 × 100 = 75 %. No rellenes el faltante con muestra de otro intervalo.');
  add('c27',2,'own','¿Cuánto es el 10 % de 80 etiquetas?', ['8 etiquetas.','10 etiquetas.','18 etiquetas.','80 etiquetas.'], '80 × 0,10 = 8.');
  add('c28',2,'own','¿Qué medida es mayor: 950 mm o 1 m?', ['1 m.','950 mm.','Son iguales.','No se pueden comparar.'], '1 m equivale a 1000 mm; 1000 es mayor que 950.');
  add('c29',2,'own','Un contenedor pesa 4 kg vacío y 19 kg lleno. ¿Cuál es la masa del contenido?', ['15 kg.','23 kg.','19 kg.','4 kg.'], 'Contenido = total − envase: 19 − 4 = 15 kg. Esto no establece una carga segura para levantar.');
  add('c30',2,'own','Un registro tiene 4, 7, 5 y 8 cajas entregadas. ¿Cuál es el total?', ['24 cajas.','20 cajas.','28 cajas.','22 cajas.'], '4 + 7 + 5 + 8 = 24.');
  add('c31',2,'own','En una tabla, 0,3 m y 30 cm corresponden a…', ['La misma longitud.','Una diferencia de 29,7 m.','Una relación de 1 a 10.','Medidas que no pueden convertirse.'], '0,3 × 100 = 30 cm. Convertir unidades evita duplicar o interpretar mal un registro.');
  add('c32',2,'own','Un aviso indica salida a las 13:25 y 45 minutos de traslado. ¿A qué hora se estima llegar?', ['14:10.','13:70.','14:25.','13:50.'], '35 minutos llevan a las 14:00; faltan 10. Estimación: 14:10.');

  // Atención, lectura y razonamiento: ejercicios originales con una única clave.
  add('l7',3,'own','Compara el código solicitado HQ-204 con las opciones. ¿Cuál coincide exactamente?', ['HQ-204.','HQ-240.','QH-204.','HQ-024.'], 'Compara prefijo, orden y dígitos; un parecido visual no basta.');
  add('l8',3,'own','La secuencia es 3, 6, 9, 12. Si sigue sumando 3, ¿qué viene?', ['15.','14.','18.','13.'], '12 + 3 = 15. La regla está indicada para evitar patrones ambiguos.');
  add('l9',3,'own','La secuencia duplica cada número: 2, 4, 8, 16. ¿Qué sigue?', ['32.','24.','18.','30.'], '16 × 2 = 32.');
  add('l10',3,'own','El pedido dice «caja 06 del pozo A». ¿Qué opción corresponde?', ['Pozo A / caja 06.','Pozo B / caja 06.','Pozo A / caja 60.','Pozo A / caja 09.'], 'Verifica todos los campos, no solo el número de caja.');
  add('l11',3,'own','Un listado dice 001, 002, 004, 005. ¿Qué número falta?', ['003.','006.','000.','007.'], 'Entre 002 y 004 falta 003.');
  add('l12',3,'own','El formato exige fecha, pozo y caja. El registro solo tiene fecha y caja. ¿Qué falta?', ['El identificador del pozo.','El nombre del color.','La temperatura del café.','Un dato que ya está completo.'], 'Revisa el registro contra los campos exigidos por ese formato.');
  add('l13',3,'own','La instrucción dice «registrar antes de entregar». ¿Qué orden cumple?', ['Registrar → entregar.','Entregar → registrar.','Entregar sin registrar.','Borrar → entregar.'], 'Respeta la relación temporal explícita en la instrucción.');
  add('l14',3,'own','Hay etiquetas A-01, A-02, A-02 y A-04. ¿Qué problema observas?', ['A-02 está duplicada y A-03 no aparece.','Las cuatro son únicas.','A-01 está duplicada.','A-04 aparece dos veces.'], 'Compara cada entrada y comprueba continuidad; no corrijas una muestra real por suposición.');
  add('l15',3,'own','Se requieren 10 cajas. Recibes 4 y luego 3. ¿Puedes declarar el pedido completo?', ['No; recibiste 7 y faltan 3.','Sí; hubo dos entregas.','Sí; recibiste más de la mitad.','No; faltan 7.'], 'El número de entregas no demuestra que la cantidad esté completa.');
  add('l16',3,'own','Dos reportes dicen 25,6 m y 26,5 m. ¿Qué puedes concluir?', ['Los valores difieren; hay que contrastar la medición original.','Ambos son iguales.','El segundo siempre es correcto.','Debo promediarlos automáticamente.'], 'Una discrepancia se investiga; no se resuelve inventando una medida intermedia.');
  add('l17',3,'own','Una tabla dice: caja 1, pozo A; caja 2, pozo B. ¿Qué pozo corresponde a caja 2?', ['Pozo B.','Pozo A.','Ambos necesariamente.','No hay información en la tabla.'], 'Lee la fila completa para mantener la asociación entre caja y pozo.');
  add('l18',3,'own','Debes ordenar 7, 3, 9 y 5 de menor a mayor. ¿Cuál es el orden?', ['3, 5, 7, 9.','9, 7, 5, 3.','3, 7, 5, 9.','5, 3, 7, 9.'], 'Compara cada par; la serie debe aumentar sin retroceder.');
  add('l19',3,'own','El procedimiento del ejercicio exige A antes de B, y B antes de C. ¿Qué secuencia cumple?', ['A → B → C.','B → A → C.','C → B → A.','A → C → B.'], 'Las dos condiciones juntas determinan A, luego B y finalmente C.');
  add('l20',3,'own','El inventario registra dos cajas cerradas y una caja abierta. ¿Cuántas cajas cerradas están confirmadas?', ['Dos.','Tres.','Una.','Ninguna.'], 'Cuenta solo los elementos que cumplen la condición solicitada.');
  add('l21',3,'own','La tarea requiere un dato que el mensaje no incluye. ¿Qué decisión mejora la precisión?', ['Pedir el dato faltante antes de ejecutarla.','Adivinar usando un caso anterior.','Escoger al azar.','Cambiar la tarea sin avisar.'], 'Reconocer información insuficiente también es razonamiento lógico.');
  add('l22',3,'own','Todas las cajas del lote X llevan sello. Esta caja no tiene sello. Según esa regla, ¿qué afirmación es válida?', ['No cumple la condición del lote X; hay que verificar su identificación.','Seguro pertenece al lote X.','Todo objeto sin sello está vacío.','La regla demuestra su composición mineral.'], 'La regla permite evaluar la condición del sello, no inventar otros atributos.');

  // Comunicación: los ejemplos no pretenden describir protocolos internos.
  add('t7',4,'own','Te dicen «trae eso de allí» y hay tres piezas. ¿Qué respondes?', ['¿Qué pieza y referencia necesitas? Quiero confirmar.','Entendido, escogeré la más grande.','No preguntaré para no parecer nuevo.','Llevaré todas sin comprobar si puedo manejarlas.'], 'Una pregunta concreta evita actuar sobre una instrucción ambigua.');
  add('t8',4,'own','Escuchas «caja doce» entre mucho ruido. ¿Cómo confirmas el pedido?', ['Repito: ¿caja 12 del pozo indicado?','Respondo sí aunque no escuché.','Llevo caja 2 porque es parecida.','Espero a que alguien adivine por mí.'], 'Repetir el identificador permite detectar un error antes de la entrega.');
  add('t9',4,'own','Tu compañero dice que vio una falla, pero tú no la viste. ¿Cómo la registras?', ['Distingo lo que reportó él de lo que observé yo.','Afirmo que la presencié.','Invento la causa más probable.','La borro porque no la vi.'], 'Un reporte fiable diferencia observación directa e información recibida.');
  add('t10',4,'own','¿Qué reporte ayuda más a localizar un problema?', ['Lugar, hora, qué observé y a quién avisé.','«Todo está mal».','«Seguro alguien tuvo la culpa».','«Creo que pasó algo, no recuerdo dónde».'], 'Los hechos concretos facilitan revisar la situación; la causa puede requerir investigación.');
  add('t11',4,'own','Te equivocas al copiar un identificador en el ejercicio. ¿Qué haces?', ['Reconozco el error y solicito la corrección conforme al formato.','Cambio varios datos para que parezcan consistentes.','Oculto la hoja.','Culpo a alguien sin evidencia.'], 'Corregir con transparencia conserva la confianza y la trazabilidad del registro.');
  add('t12',4,'own','En entrevista te preguntan si operaste una perforadora. No lo has hecho. ¿Qué dices?', ['No he operado una; estoy estudiando y dispuesto a aprender con supervisión.','Sí, porque vi videos.','Sí, porque completé un quiz.','Que conozco todos los modelos.'], 'Describe tu experiencia real y cómo te preparas, sin convertir el estudio en experiencia de operación.');
  add('t13',4,'own','¿Cuál es un ejemplo útil para demostrar aprendizaje rápido?', ['Una situación real donde aprendí una tarea, pedí ayuda y mejoré.','Una experiencia inventada de perforación.','Una lista de palabras que no entiendo.','Decir que nunca necesito instrucciones.'], 'Un ejemplo real permite explicar acciones y resultados aunque venga de otro trabajo o de tus estudios.');
  add('t14',4,'own','Un cliente pregunta por una información que no conoces. ¿Cómo respondes?', ['Confirmaré el dato con la persona responsable.','Invento una cifra aproximada.','Aseguro que todo está perfecto.','Prometo un resultado que no puedo verificar.'], 'La precisión y los límites de tu conocimiento forman parte de una buena comunicación.');
  add('t15',4,'own','¿Qué frase es más clara para pedir una demostración?', ['Es mi primera vez con esta tarea; ¿puede mostrarme el método y verificar que lo entendí?','Yo sé hacerlo, aunque no sea cierto.','Hágalo usted siempre.','No importa el método, lo intentaré.'], 'Explica qué necesitas aprender y propone comprobar tu comprensión.');
  add('t16',4,'own','Hay desacuerdo sobre qué caja entregar. ¿Qué haces?', ['Contrasto el pedido y los identificadores con el responsable.','Entrego la primera para terminar.','Decido por quién habla más fuerte.','Mezclo el contenido de las dos.'], 'Resolver la discrepancia con datos evita multiplicar el error.');
  add('t17',4,'own','¿Qué informa mejor tu estado de una tarea?', ['Completé A; B queda pendiente porque falta confirmar el código.','«Todo listo», aunque falta una parte.','«Después vemos», sin detallar pendientes.','No reportar hasta el siguiente día.'], 'Separa lo terminado, lo pendiente y la razón del pendiente.');
  add('t18',4,'own','Para aprender de una indicación, ¿qué combinación sirve mejor?', ['Escuchar, preguntar, repetir lo entendido y aceptar correcciones.','Interrumpir siempre y actuar antes de escuchar.','Memorizar sonidos sin entender.','Evitar cualquier pregunta.'], 'Esta práctica de comunicación te ayuda a detectar dudas antes de actuar.');

  // Campo: apoyo bajo supervisión, preparación, muestras y relevo.
  add('f1',6,'career','Llegas al primer turno. ¿Qué buscas entender en la reunión previa?', ['Las tareas previstas y los peligros asociados.','Solo la hora de almuerzo.','Qué controles puedo saltarme.','Cómo cambiar la meta sin avisar.'], 'La reunión previa presenta actividades y riesgos. Pregunta por tu función concreta.');
  add('f2',6,'career','¿Cuál puede ser una tarea de apoyo de un ayudante?', ['Preparar y organizar muestras para su entrega.','Certificar por su cuenta el valor del yacimiento.','Rediseñar la perforadora sin autorización.','Aprobar todas las maniobras como jefe.'], 'En el sector se describen tareas de muestras, equipo y preparación del sitio, coordinadas con la cuadrilla.');
  add('f3',6,'career','Al entregar el turno, ¿qué información interesa a la siguiente cuadrilla?', ['El trabajo realizado, las condiciones y los pendientes relevantes.','Solo cuántos puntos logré en un juego.','Rumores sin relación con la tarea.','Únicamente mi hora de llegada.'], 'El relevo comunica información operativa y de seguridad; evita que el siguiente equipo empiece sin contexto.');
  add('f4',6,'career','¿Qué esperas del trabajo diario de una cuadrilla?', ['Coordinación continua entre perforista, ayudantes y supervisión.','Cada persona decide todo de forma aislada.','El ayudante nunca comunica observaciones.','La comunicación termina al iniciar el motor.'], 'Las tareas y los relevos requieren comunicación constante; el puesto de ayudante forma parte de un equipo.');
  add('f5',6,'competence','Al preparar cajas de testigos, ¿qué debe conservarse?', ['La secuencia requerida y su identificación.','Solo las piezas visualmente más bonitas.','Una mezcla de intervalos para llenar huecos.','Un orden elegido por el color de la roca.'], 'Conserva secuencia, marcas e identificación conforme al procedimiento de muestras.');
  add('f6',6,'competence','Un testigo delicado se deshace fácilmente. ¿Qué haces?', ['Pido el método de preservación y evito manipularlo innecesariamente.','Lo lavo a presión sin consultar.','Lo mezclo con uno resistente.','Lo descarto por verse frágil.'], 'Las muestras delicadas requieren preservación y prevención de contaminación superficial.');
  add('f7',6,'competence','Un producto de mezcla tiene etiqueta diferente a la instrucción. ¿Qué haces?', ['Detengo esa preparación y confirmo producto e información de seguridad.','Uso la dosis de cualquier otro saco.','Lo identifico por el olor.','Mezclo primero y pregunto después.'], 'Para preparar fluidos se comprueban etiquetas, información de seguridad y el procedimiento de mezcla.');
  add('f8',6,'competence','¿Qué apoyo puede incluir el cuidado de herramientas?', ['Inspecciones y mantenimiento básico asignados, siguiendo el procedimiento.','Reparar cualquier falla eléctrica sin formación.','Intervenir barras que giran.','Ajustar presiones a prueba y error.'], 'La competencia de ayudante incluye tareas rutinarias bajo supervisión; confirma capacitación y alcance antes de hacerlas.');
  add('f9',6,'surfaceJob','¿Qué describe la vacante de ayudante de Boart en superficie como parte de la jornada?', ['Comprobaciones previas de equipo y seguridad.','Empezar sin revisar el sitio.','Analizar mineral en un laboratorio por cuenta propia.','Diseñar explosivos.'], 'Es una referencia del sector en Australia, no el listado contractual de Hubbard.');
  add('f10',6,'surfaceJob','La cuadrilla se prepara para un movimiento de equipo. ¿En qué podrías apoyar?', ['En carga, descarga y organización que me asignen con el método seguro.','Conduciendo cualquier vehículo sin autorización.','Decidiendo el emplazamiento yo solo.','Ubicándome debajo de una carga.'], 'El puesto de referencia incluye apoyo logístico y al montaje. La maniobra necesita personal competente.');
  add('f11',6,'surfaceJob','¿Limpiar y mantener el área ordenada forma parte del apoyo?', ['Sí, aparece entre las tareas de ayudante del sector.','No; solo importa la profundidad.','Solo antes de una visita.','Solo cuando nadie perfora en el proyecto.'], 'La referencia describe el mantenimiento de un área limpia y ordenada como tarea habitual.');
  add('f12',6,'surfaceJob','¿Qué describe mejor el puesto inicial?', ['Apoyar al perforista o supervisor en labores para operar de forma segura.','Ser automáticamente operador autónomo desde el primer día.','Trabajar sin instrucciones.','Realizar únicamente tareas de oficina.'], 'El apoyo abarca varias labores. Las asignaciones concretas dependen del proyecto y de tu formación.');
  add('f13',6,'traffic','Un camión maniobra y no sabes si el operador te vio. ¿Qué haces?', ['Me mantengo fuera de su trayectoria y solicito autorización para aproximarme.','Cruzo detrás porque llevo chaleco.','Me pongo junto a una rueda.','Golpeo el vehículo mientras retrocede.'], 'Evita puntos ciegos y zonas de movimiento. La alta visibilidad no confirma que te hayan visto.',true);
  add('f14',6,'traffic','Te piden hacer señales para una maniobra que no conoces. ¿Qué respondes?', ['Necesito formación y designación antes de asumir esa función.','Inventaré gestos fáciles de entender.','Todos los gestos significan lo mismo.','Ser ayudante basta para dirigir cualquier maniobra.'], 'El señalista necesita competencia, señales acordadas y comunicación clara.');
  add('f15',6,'traffic','Cambió el acceso peatonal por una maniobra. ¿Qué debes consultar?', ['La ruta y el control de tránsito actualizados.','El atajo por debajo de la máquina.','La ruta de ayer sin mirar cambios.','Solo si el vehículo es grande.'], 'El plan de tránsito debe adaptarse cuando cambian las condiciones del lugar.');
  add('f16',6,'traffic','¿Dónde debes evitar ubicarte cerca de una máquina pesada?', ['En su radio de giro y entre objetos donde podría aplastarme.','En la ruta peatonal designada y libre.','En el punto seguro establecido.','En el lugar autorizado fuera de la maniobra.'], 'Mantente fuera del radio de movimiento y de posibles zonas de atrapamiento.',true);

  add('h1',7,'tools','Una llave tiene mordazas desgastadas. ¿Qué decides?', ['No usarla y pedir una herramienta en condiciones.','Usarla con mayor fuerza.','Compensar con guantes más gruesos.','Golpearla para que ajuste.'], 'Revisa defectos antes de usar herramientas; el desgaste puede hacer que resbalen.');
  add('h2',7,'tools','No encuentras la herramienta indicada. ¿Sirve un destornillador como cincel?', ['No; busco la herramienta apropiada.','Sí, cualquier punta metálica sirve.','Sí, si golpeo con cuidado.','Sí, si otro trabajador lo hizo.'], 'Usar una herramienta para una función no prevista aumenta el riesgo.');
  add('h3',7,'tools','¿Cómo entregas una herramienta manual a tu compañero?', ['Directamente y con el mango hacia quien la recibe.','Lanzándola para ahorrar tiempo.','Con la punta hacia su cara.','Dejándola caer desde arriba.'], 'Entrega las herramientas sin lanzarlas; orienta el mango hacia quien la recibe.');
  add('h4',7,'tools','Después de una tarea, ¿qué cuidado básico corresponde a las herramientas?', ['Limpiarlas, mantenerlas secas y guardarlas apropiadamente.','Dejarlas en bordes elevados.','Ocultar las dañadas entre las demás.','Dejar puntas expuestas en el paso.'], 'El almacenamiento adecuado evita deterioro y contactos accidentales.');
  add('h5',7,'electric','Una herramienta eléctrica portátil tiene cable pelado. ¿Qué haces?', ['La retiro de uso, la identifico y aviso para revisión calificada.','La reparo con cinta mientras está conectada.','La uso si no llueve.','La sujeto por el cable.'], 'El equipo defectuoso se aparta; no improvises reparaciones de campo.',true);
  add('h6',7,'electric','Al desconectar una herramienta portátil, ¿de dónde se tira?', ['Del enchufe, sin tirar del cable.','Del cable con fuerza.','De la carcasa hasta arrancar el enchufe.','De cualquier conductor visible.'], 'Tirar del cable puede dañar la conexión y generar peligro eléctrico.');
  add('h7',7,'electric','Para cambiar un accesorio de una herramienta eléctrica portátil, ¿qué es necesario?', ['Desconectar su alimentación conforme a las instrucciones.','Mantener el gatillo presionado.','Solo bajar la velocidad.','Pedir que alguien sostenga el accesorio girando.'], 'Desconecta antes de ajustar o cambiar accesorios; sigue el manual específico.',true);
  add('h8',7,'electric','¿Puedes quitar la pata de tierra de un enchufe para que entre?', ['No; se requiere una conexión adecuada y revisión competente.','Sí, si el enchufe tiene tres patas.','Sí, si la tarea es breve.','Sí, con una herramienta manual.'], 'No elimines una protección eléctrica para adaptar una conexión.',true);
  add('h9',7,'handling','¿El peso es el único factor al evaluar una carga manual?', ['No; también importan forma, agarre, ruta, postura y frecuencia.','Sí, todo depende de un único número.','Sí, si uso botas.','No; únicamente importa su color.'], 'Una carga ligera puede ser difícil de manejar por su forma o por las condiciones.');
  add('h10',7,'handling','La caja tapa la vista de tus pies. ¿Qué debes evaluar?', ['Otro método que permita moverla sin perder visibilidad de la ruta.','Caminar más rápido.','Cerrar los ojos y recordar la ruta.','Llevar dos cajas para equilibrarme.'], 'Una carga que impide ver el paso aumenta el riesgo; reevalúa la tarea.');
  add('h11',7,'handling','El contenido de un contenedor se desplaza. ¿Qué problema puede crear?', ['Cambiar su equilibrio y dificultar el control.','Disminuir siempre su masa.','Eliminar el esfuerzo.','Garantizar un agarre firme.'], 'Las cargas inestables pueden cambiar su centro de gravedad durante el manejo.');
  add('h12',7,'handling','¿Qué condición aumenta el riesgo al mover cajas manualmente?', ['Piso resbaloso y poca iluminación.','Ruta despejada y visible.','Carga estable y método evaluado.','Ayuda adecuada y coordinación.'], 'El riesgo depende también del entorno y del ritmo de trabajo.');
  add('h13',7,'sling','Una eslinga textil presenta cortes. ¿Qué haces?', ['La aparto de uso y comunico el daño.','La uso para cargas pequeñas sin consultar.','Hago un nudo sobre el corte.','La oculto debajo de la carga.'], 'Los cortes y daños de costura pueden hacer inutilizable una eslinga.',true);
  add('h14',7,'sling','¿Dónde se consulta la capacidad adecuada de una eslinga?', ['En la identificación y las tablas del fabricante para la configuración.','En su color sin más información.','En cuánto puedo levantar yo.','En el tamaño del gancho solamente.'], 'La capacidad depende de la eslinga y del modo de uso; requiere selección competente.');
  add('h15',7,'sling','¿Un nudo es un método válido para acortar una eslinga textil?', ['No; sigo los métodos autorizados del sistema.','Sí, si el nudo queda apretado.','Sí, si lo cubro con cinta.','Sí, con cualquier tipo de carga.'], 'No acortes ni alargues una eslinga mediante nudos.',true);
  add('h16',7,'sling','Una carga tiene bordes que pueden cortar la eslinga. ¿Qué necesita evaluar el responsable?', ['La protección de bordes y la selección del aparejo adecuado.','Solo cómo levantar más rápido.','Si pintar el borde elimina el riesgo.','El color de la eslinga, únicamente.'], 'Los bordes y la abrasión pueden dañar la eslinga; la maniobra requiere planificación.');

  add('a1',8,'labels','¿Qué aporta la etiqueta de un producto químico?', ['Identificación, advertencias de peligro y precauciones.','Una garantía de que no hay riesgos.','La profundidad del pozo.','La autorización para mezclarlo con todo.'], 'Lee las advertencias y precauciones; consulta también la ficha que corresponde al producto.');
  add('a2',8,'labels','Encuentras un envase con etiqueta ilegible. ¿Cómo lo identificas?', ['Solicito su identificación correcta antes de usarlo.','Lo huelo de cerca.','Lo pruebo con la piel.','Supongo que contiene agua.'], 'Una etiqueta debe ser legible; apariencia y olor no sustituyen una identificación fiable.');
  add('a3',8,'labels','En una etiqueta, ¿qué describen las indicaciones de peligro?', ['La naturaleza de los peligros del producto.','Solo su precio.','El número de cajas de testigos.','El permiso de conducción.'], 'Distingue peligros de precauciones: unos describen el daño posible; otras orientan cómo reducir la exposición.');
  add('a4',8,'labels','Si transfieren un químico a otro recipiente, ¿qué debes confirmar?', ['Que conserve la identificación y el etiquetado exigidos por el procedimiento.','Que el recipiente parezca una botella de bebida.','Que no haya ninguna marca.','Que solo una persona recuerde su contenido.'], 'El recipiente secundario debe identificarse conforme al procedimiento aplicable. WHMIS es una referencia canadiense.');
  add('a5',8,'spill','Hay un derrame desconocido y no estás capacitado para limpiarlo. ¿Qué haces?', ['Me retiro de la exposición, alerto y solicito la respuesta prevista.','Lo recojo con la mano.','Mezclo un neutralizante al azar.','Lo empujo hacia el drenaje.'], 'Solo personal capacitado y equipado debe intervenir; ante duda, evacúa el área afectada y pide ayuda.',true);
  add('a6',8,'spill','¿Todo material absorbente sirve para cualquier derrame?', ['No; debe ser compatible con el químico.','Sí, mientras sea barato.','Sí, si absorbe agua.','Sí, si está en un balde.'], 'La selección del kit y los materiales depende del producto; algunos materiales pueden reaccionar.');
  add('a7',8,'spill','¿Por qué no se debe enviar un derrame químico al desagüe?', ['Puede contaminar y extender el incidente fuera del área.','Porque siempre se solidifica.','Porque todos los drenajes recuperan el químico.','Porque se pierde el color del suelo.'], 'Protege los drenajes mediante el plan de respuesta y personal autorizado; reporta afectación ambiental.');
  add('a8',8,'spill','¿Qué se hace con residuos de limpieza de un derrame?', ['Se gestionan identificados y según el procedimiento de residuos.','Se mezclan todos aunque sean incompatibles.','Se dejan sin marca en cualquier lugar.','Se queman por cuenta propia.'], 'No mezcles residuos incompatibles; usa recipientes y disposición adecuados.');
  add('a9',8,'respirator','¿Quién debe seleccionar un respirador para una exposición de trabajo?', ['Personal competente que evalúe el contaminante y la exposición.','Yo, escogiendo el que se vea más grande.','Quien tenga una mascarilla sobrante.','Cualquiera que recomiende una marca.'], 'La selección requiere evaluar peligro, concentración, límites y prestaciones del respirador.');
  add('a10',8,'respirator','¿Un filtro para partículas sirve automáticamente contra gases y vapores?', ['No; filtros y cartuchos tienen funciones específicas.','Sí, todos limpian el aire de igual forma.','Sí, si cubre la nariz.','Sí, si es del mismo color.'], 'El tipo de protección debe corresponder al contaminante. No intercambies funciones por suposición.');
  add('a11',8,'respirator','¿Debe ser el respirador la primera y única medida frente a una exposición?', ['No; se evalúan primero otros controles y su eficacia.','Sí, siempre basta una mascarilla.','Sí, así no hay que medir exposición.','Sí, permite ignorar ventilación y procedimientos.'], 'La protección respiratoria forma parte de un programa y de una estrategia de control de exposición.');
  add('a12',8,'respirator','Te prestan un respirador sin revisar si corresponde al peligro. ¿Qué haces?', ['Solicito la evaluación y formación necesarias antes de exponerme.','Lo uso porque tener cualquiera basta.','Cambio el cartucho por uno al azar.','Me acerco al polvo para probarlo.'], 'El equipo incorrecto o mal usado no garantiza protección.');
  add('a13',8,'silica','¿Perforar o triturar roca puede generar polvo de sílice respirable?', ['Sí, según el material y la actividad.','No, porque toda roca es inocua.','Solo si hay petróleo.','Solo en trabajos de oficina.'], 'La perforación y trituración de materiales con sílice pueden producir partículas respirables.');
  add('a14',8,'silica','¿Qué vía de exposición destaca para el polvo de sílice respirable?', ['La inhalación de partículas muy pequeñas.','Solo tocar roca con botas.','Mirar las cajas.','Leer el registro del turno.'], 'Las partículas respirables pueden llegar al sistema respiratorio y causar enfermedades graves.');
  add('a15',8,'silica','¿Por qué importa controlar una exposición a sílice aunque no cause dolor inmediato?', ['Puede causar daño serio con la exposición.','Todo peligro avisa con dolor instantáneo.','Si no huele, no existe.','Solo importa si ensucia la ropa.'], 'La ausencia de molestia inmediata no demuestra ausencia de exposición peligrosa.');
  add('a16',8,'silica','¿Qué afirmación evita subestimar el polvo de roca?', ['Su composición y la exposición deben evaluarse.','Todas las partículas visibles son lo único peligroso.','La sílice nunca está en arena o piedra.','Un buen estado físico evita cualquier daño.'], 'Los materiales pueden contener sílice y generar partículas muy pequeñas; no evalúes el peligro solo a simple vista.');

  add('e1',9,'emergency','Antes del primer trabajo, ¿qué debes conocer del plan de emergencia?', ['Cómo alertar, por dónde evacuar y dónde reunirse.','Solo dónde guardar mi mochila.','La contraseña del teléfono del jefe.','La producción de la semana pasada.'], 'Conoce las instrucciones de tu función, las rutas y el punto de reunión.');
  add('e2',9,'emergency','Suena la orden de evacuación. ¿Qué haces con una herramienta que dejaste?', ['Sigo la evacuación; no me retraso por recuperarla.','Regreso por la herramienta.','Espero a terminar el inventario.','Me escondo para no dejar la tarea incompleta.'], 'La seguridad de las personas tiene prioridad. Sigue la ruta y las instrucciones del plan.',true);
  add('e3',9,'emergency','En el punto de reunión falta una persona. ¿Qué haces?', ['Informo al responsable del conteo; no inicio un rescate improvisado.','Vuelvo solo a buscarla.','Doy por hecho que se fue a casa.','Me retiro sin avisar.'], 'El conteo permite activar la respuesta. Comunica la ausencia y sigue las instrucciones del plan.');
  add('e4',9,'emergency','La radio principal falla durante una emergencia. ¿Qué conviene haber previsto?', ['Un medio alternativo de comunicación y contactos definidos.','Que cada persona improvise.','Solo una lista sin acceso desde el campo.','No comunicar hasta que vuelva la señal.'], 'El plan debe considerar fallas de comunicación y las responsabilidades de respuesta.');
  add('e5',9,'fire','Un incendio crece y no tienes capacitación. ¿Qué haces?', ['Activo la alerta y evacúo conforme al plan.','Pruebo distintos líquidos para apagarlo.','Busco un extintor sin avisar a nadie.','Entro al humo para ver el origen.'], 'No combatas un fuego sin competencia ni medios adecuados; alerta y evacúa.',true);
  add('e6',9,'fire','¿Se usa agua sobre equipo eléctrico energizado en llamas?', ['No; puede aumentar el peligro de electrocución.','Sí, siempre es lo primero.','Sí, si el recipiente es plástico.','Sí, si llevo casco.'], 'Reconoce el peligro y activa la respuesta; la selección de extintor y su uso requieren formación.',true);
  add('e7',9,'fire','¿Todos los extintores sirven para todos los materiales en llamas?', ['No; están diseñados para tipos de fuego específicos.','Sí, solo cambia el tamaño.','Sí, si son rojos.','Sí, si están nuevos.'], 'El material que arde determina la selección; lee su identificación y recibe entrenamiento.');
  add('e8',9,'fire','El fuego compromete tu salida. ¿Qué tiene prioridad?', ['Retirarme hacia una salida segura y alertar.','Continuar intentando apagarlo a toda costa.','Rescatar herramientas primero.','Cerrar todas las salidas sin consultar.'], 'Mantener una vía segura de escape es esencial; si el fuego crece, evacúa.',true);
  add('e9',9,'confined','Un tanque grande, ¿puede ser un espacio confinado?', ['Sí; el tamaño no descarta esa condición.','No, solo lo son los espacios muy pequeños.','No, si está pintado.','Solo si es de madera.'], 'Importan acceso, ocupación prevista y peligros, no únicamente el tamaño.');
  add('e10',9,'confined','Un pozo abierto al cielo, ¿queda automáticamente libre del riesgo de espacio confinado?', ['No; el acceso y los peligros deben evaluarse.','Sí, el cielo elimina todos los gases.','Sí, si se ve el fondo.','Sí, si hay una escalera cerca.'], 'Algunos pozos y zanjas pueden reunir condiciones de espacio confinado.');
  add('e11',9,'confined','¿Basta mirar un tanque para asegurar que su atmósfera permite entrar?', ['No; requiere evaluación y pruebas por personal capacitado.','Sí, si no hay humo.','Sí, si no tiene olor.','Sí, si otro entró ayer.'], 'La atmósfera se evalúa desde fuera con medios adecuados antes de una entrada autorizada.',true);
  add('e12',9,'confined','¿Las condiciones de un espacio confinado pueden cambiar durante el trabajo?', ['Sí; por eso se necesitan controles y vigilancia adecuados.','No, una revisión sirve para siempre.','Solo cambia el color de las paredes.','No, si la puerta sigue abierta.'], 'Las actividades y el entorno pueden introducir nuevos peligros o cambiar la atmósfera.');
  add('e13',9,'rescue','Un compañero colapsa dentro de un tanque. No estás formado para rescate. ¿Qué haces?', ['Activo la emergencia y no entro a exponerme.','Entro aguantando la respiración.','Entro con una mascarilla cualquiera.','Pido que entre otro ayudante sin equipo.'], 'El rescate requiere personal entrenado y equipado. Una entrada improvisada puede producir otra víctima.',true);
  add('e14',9,'rescue','¿El permiso de entrada sustituye todos los controles físicos?', ['No; documenta una evaluación y controles que deben verificarse.','Sí, basta firmarlo.','Sí, elimina cualquier atmósfera peligrosa.','Sí, permite cambiar la tarea sin revisar.'], 'Un documento no vuelve seguro un espacio por sí solo.');
  add('e15',9,'rescue','El vigía de una entrada tiene otra tarea que lo distrae. ¿Qué problema hay?', ['No puede cumplir adecuadamente su vigilancia y comunicación.','Ninguno, vigilar es opcional.','Así aprende más rápido.','Solo importa que esté cerca del tanque.'], 'El vigía debe permanecer fuera, monitorear y mantener comunicación sin tareas que interfieran.');
  add('e16',9,'rescue','Hay alarma del monitor atmosférico en una entrada autorizada. ¿Qué corresponde?', ['Salir inmediatamente conforme al procedimiento y comunicar.','Esperar a sentir síntomas.','Tapar el sonido de la alarma.','Desconectar el monitor.'], 'Una alarma indica una condición que requiere evacuación y respuesta; no la ignores.',true);

  add('r1',10,'heat','Estás en tu primer día de trabajo con mucho calor. ¿Qué debes confirmar?', ['El plan de adaptación gradual, pausas y agua disponible.','Cómo trabajar de inmediato al máximo ritmo.','Que estar en forma elimina el calor.','Cómo evitar cualquier pausa.'], 'Los nuevos trabajadores necesitan aclimatización y controles adecuados al trabajo.');
  add('r2',10,'heat','¿La buena condición física sustituye la aclimatización al calor?', ['No.','Sí, completamente.','Sí, si soy joven.','Sí, si trabajé antes en oficina.'], 'La adaptación al ambiente es necesaria incluso con buena condición física.');
  add('r3',10,'heat','¿Qué conjunto ayuda a reducir el estrés térmico?', ['Controles de la tarea, descanso en zona fresca y acceso a agua.','Solo trabajar más rápido.','Solo quitar el EPP requerido sin consultar.','Esperar al final del turno para beber.'], 'Las medidas se seleccionan según la exposición; no dependen únicamente de aguantar.');
  add('r4',10,'heat','¿Por qué se vigila a los compañeros durante trabajo con calor?', ['Pueden no reconocer a tiempo sus propias señales de malestar.','Porque el calor solo afecta a quien está solo.','Para impedir que pidan ayuda.','Porque la vigilancia elimina la necesidad de pausas.'], 'La observación entre compañeros ayuda a solicitar asistencia a tiempo.');
  add('r5',10,'lightning','Oyes truenos mientras trabajas al aire libre. ¿Qué significa?', ['La tormenta está suficientemente cerca para representar peligro.','No hay peligro hasta que llueva fuerte.','Solo hay peligro si toco agua.','El casco impide que me alcance un rayo.'], 'El trueno indica riesgo de rayos; aplica el plan de tormentas y busca refugio seguro.',true);
  add('r6',10,'lightning','¿Qué refugio identifica NOAA/NWS como opción segura frente a rayos?', ['Un edificio sólido o vehículo cerrado con techo rígido adecuado.','Un árbol alto.','La base del mástil.','Un cobertizo abierto cualquiera.'], 'Sigue el refugio designado por el sitio; los lugares abiertos y objetos altos no brindan protección.');
  add('r7',10,'lightning','Una tormenta amenaza y la tarea no se puede detener rápido. ¿Qué haces?', ['No la inicio; comunico y aplico el plan meteorológico.','La empiezo para adelantar unos minutos.','Espero a que caiga un rayo al lado.','Me ubico sobre una estructura alta.'], 'Planifica para poder llegar al refugio antes de la exposición peligrosa.');
  add('r8',10,'lightning','¿Trabajar junto a maquinaria alta durante una tormenta elimina el riesgo?', ['No; debo alejarme y seguir la respuesta prevista.','Sí, el metal siempre me protege afuera.','Sí, si toco el equipo.','Sí, si todavía no está lloviendo.'], 'Evita estructuras altas y maquinaria grande al aire libre durante la tormenta.',true);
  add('r9',10,'fatigue','Te cuesta concentrarte y reaccionas más lento. ¿Qué debes considerar?', ['La fatiga puede afectar decisiones y seguridad; debo comunicarlo.','Que solo importa completar la meta.','Que nunca afecta a una persona joven.','Que se soluciona ocultándola.'], 'La fatiga reduce atención, memoria y tiempo de reacción.');
  add('r10',10,'fatigue','¿Cuál puede contribuir a la fatiga laboral?', ['Dormir poco y jornadas o turnos exigentes.','Solo tener un casco nuevo.','Solo leer un manual.','Exclusivamente el trabajo de oficina.'], 'El sueño insuficiente y las exigencias del trabajo pueden contribuir; reconoce y comunica el problema.');
  add('r11',10,'fatigue','Estás muy fatigado y te asignan conducir. ¿Qué haces?', ['Comunico mi estado y no realizo la tarea de riesgo en esas condiciones.','Conduzco más rápido para terminar antes.','Abro la ventana y doy por resuelto el problema.','No digo nada para conservar la asignación.'], 'No realices tareas de alto riesgo como conducción cuando estás fatigado; informa al supervisor.',true);
  add('r12',10,'fatigue','¿Qué plan favorece manejar la fatiga?', ['Descanso suficiente, pausas y comunicación con supervisión.','Eliminar el sueño durante los días de trabajo.','Ocultar errores de concentración.','Sustituir siempre el descanso por cafeína.'], 'La gestión incluye descanso y organización del trabajo; una bebida no sustituye esas medidas.');
  add('r13',10,'alone','Te asignan una tarea aislada sin señal de celular. ¿Qué debes confirmar?', ['Un medio alternativo de comunicación y el plan de contacto.','Que si no hay señal nadie puede ayudar y da igual.','Cómo hacerla sin avisar dónde estaré.','Solo el color de la radio.'], 'Cuando la telefonía es poco fiable se necesitan alternativas adecuadas a la tarea.');
  add('r14',10,'alone','Para una tarea remota, ¿qué información conviene dejar al contacto designado?', ['Destino, ruta y tiempos previstos de llegada y regreso.','Solo mi nombre de usuario en el juego.','Una ubicación inventada.','Únicamente el número de botas.'], 'El plan de contacto permite detectar demoras y activar una respuesta.');
  add('r15',10,'alone','Un trabajador no cumple un contacto programado. ¿Qué debe ocurrir?', ['Activar el procedimiento de seguimiento y emergencia previsto.','Asumir que todo está bien indefinidamente.','Borrar el registro.','Ir solo a una zona peligrosa sin avisar.'], 'El protocolo debe definir cuándo y cómo actuar ante un contacto incumplido.');
  add('r16',10,'alone','¿Trabajar aislado solo significa estar lejos de una ciudad?', ['No; también importa si otras personas pueden verte, oírte o asistirte.','Sí, únicamente la distancia a la ciudad.','Solo si trabajo de noche.','Solo si no tengo vehículo.'], 'La evaluación considera lugar, tarea, comunicación y consecuencias de una emergencia.');

  const field = [
    {title:'Antes de salir',src:'fatigue',ids:['r9','r11'],tasks:['Revisa si descansaste y si puedes concentrarte.','Comunica cualquier condición que afecte la tarea asignada.'],watch:'No ocultes somnolencia para conseguir una asignación.',say:'Hoy me cuesta mantener la atención; necesito informar mi estado antes de asumir una tarea de riesgo.'},
    {title:'Reunión previa y relevo',src:'career',ids:['f1','f3'],tasks:['Escucha el plan y los pendientes del turno anterior.','Confirma quién te supervisa y qué apoyo te corresponde.'],watch:'No confundas escuchar una tarea con estar autorizado para operarla.',say:'Entendí el objetivo. ¿Cuál será mi tarea y qué quedó pendiente del turno anterior?'},
    {title:'Conocer el área',src:'emergency',ids:['e1','e4'],tasks:['Ubica rutas de salida, punto de reunión y medios de alerta.','Pregunta quién responde ante una emergencia.'],watch:'En una emergencia, sigue tu función y las instrucciones del plan.',say:'¿Cómo activo la alerta y a qué punto de reunión debo dirigirme?'},
    {title:'Revisión previa asignada',src:'surfaceJob',ids:['f9','f12'],tasks:['Apoya las comprobaciones previas con la lista del sitio.','Comunica observaciones al responsable.'],watch:'La revisión no implica reparar una falla por cuenta propia.',say:'Esta comprobación no coincide con la lista; necesito que la revisemos antes de continuar.'},
    {title:'Organizar herramientas',src:'tools',ids:['h1','h4'],tasks:['Identifica herramientas y revisa defectos antes de usarlas.','Guarda y entrega cada herramienta de forma adecuada.'],watch:'No sustituyas una herramienta por otra para una función no prevista.',say:'Esta llave tiene desgaste visible. Solicito una en condiciones para la tarea.'},
    {title:'Apoyo a movimientos',src:'traffic',ids:['f13','f14'],tasks:['Respeta rutas peatonales, puntos ciegos y zonas de giro.','Asume señalización solo si estás formado y designado.'],watch:'No entres en la trayectoria de la máquina ni entre objetos que podrían aplastarte.',say:'Permanezco fuera de la maniobra. Confirmen la ruta segura para aproximarme.'},
    {title:'Apoyo durante la perforación',src:'competence',ids:['f8','s1'],tasks:['Realiza únicamente el apoyo asignado y supervisado.','Mantén atención a cambios, riesgos y condiciones del equipo.'],watch:'Barras, tubos y mantenimiento requieren capacitación y procedimientos específicos.',say:'No he hecho esta tarea antes. Necesito demostración y supervisión para aprenderla.'},
    {title:'Recibir y cuidar muestras',src:'competence',ids:['f5','f6'],tasks:['Conserva secuencia, identificación y marcas según el procedimiento.','Protege muestras delicadas de daño y contaminación.'],watch:'No rellenes faltantes ni reordenes muestras por apariencia.',say:'Este tramo se fragmenta; confirmemos cómo conservarlo y registrarlo.'},
    {title:'Preparar productos asignados',src:'labels',ids:['a2','f7'],tasks:['Comprueba la identidad del producto y la información de seguridad.','Confirma que corresponda a la instrucción recibida.'],watch:'Una apariencia parecida no valida una mezcla.',say:'La etiqueta no se puede leer. No usaré el producto hasta confirmar su identidad.'},
    {title:'Cambios y condiciones del turno',src:'heat',ids:['r1','r3'],tasks:['Sigue pausas y controles del plan de calor.','Observa tu estado y el de los compañeros.'],watch:'La exigencia y el clima pueden cambiar la exposición.',say:'El calor y el esfuerzo aumentaron; revisemos los controles y las pausas previstas.'},
    {title:'Orden y cierre de tareas',src:'spill',ids:['a5','a8'],tasks:['Reporta derrames y gestiona residuos según la tarea autorizada.','Usa solo los materiales y la respuesta adecuados al producto.'],watch:'No limpies un químico desconocido ni lo envíes al drenaje.',say:'Hay un derrame en esta zona. Desconozco el producto y solicito la respuesta prevista.'},
    {title:'Entregar el turno',src:'career',ids:['t17','f4'],tasks:['Comunica lo realizado, las condiciones y los pendientes.','Participa en el relevo y entrega los registros requeridos.'],watch:'No declares una tarea completa si queda una comprobación pendiente.',say:'Se completó esta parte; queda esta revisión pendiente y ya se informó al responsable.'}
  ];

  const resources = [
    {id:'vdci',type:'video',src:'dci',title:'Reconocer una interfaz de perforación: DCi',lang:'Inglés / demostración visual',url:'https://www.youtube.com/watch?v=m7mm0lz1SZc',learn:'Observa controles, lecturas y la separación del operador respecto del equipo.',note:'Video enlazado por el fabricante. La configuración y las funciones pertenecen a ese sistema.',prompt:'¿Qué información aparece en el panel y quién debería decidir los parámetros?',cat:1},
    {id:'vloader',type:'video',src:'loader',title:'Perforadora LF160 y cargador de barras FL262',lang:'Inglés / demostración visual',url:'https://www.youtube.com/watch?v=H3pf2857Bes',learn:'Reconoce mástil, barras, barreras y manejo mecanizado.',note:'Ejemplo de equipo del fabricante; no está confirmado que sea el utilizado por Hubbard.',prompt:'¿Cómo cambia la exposición de las manos al usar manejo mecanizado?',cat:7},
    {id:'vsilica',type:'video',src:'silica',title:'Reconocer el peligro de sílice en el trabajo',lang:'Inglés',url:'https://www.youtube.com/watch?v=-kQmLYqIR2A',learn:'Video enlazado por OSHA sobre exposición a sílice.',note:'Principios de exposición; la normativa y las tareas del video son estadounidenses.',prompt:'¿Por qué no basta evaluar el polvo solo por lo que se ve?',cat:8},
    {id:'rday',type:'lectura',src:'career',title:'Cómo es trabajar en una cuadrilla de perforación',lang:'Inglés',learn:'Conoce tareas de apoyo, preparación y relevos.',note:'Relato del sector de 2018. No confirma jornadas ni rotaciones de Hubbard.',prompt:'Enumera tres tareas que podrías apoyar bajo supervisión.',cat:6},
    {id:'rjob',type:'lectura',src:'surfaceJob',title:'Un ejemplo real de funciones de ayudante',lang:'Inglés',learn:'Consulta el apartado de funciones de una vacante del fabricante.',note:'Puesto australiano: sus licencias, roster y requisitos no se trasladan a Ecuador.',prompt:'¿Qué controles previos y apoyos logísticos aparecen?',cat:6},
    {id:'runit',type:'manual',src:'competence',title:'Mapa de competencias: ayudante de diamantina',lang:'Inglés · PDF',learn:'Ubica preparación, apoyo, muestras, fluidos y mantenimiento básico.',note:'Unidad formativa australiana. Es un mapa de estudio, no una certificación local ni un manual de máquina.',prompt:'¿Qué necesitas aprender en campo antes de ejecutar cada tarea?',cat:6},
    {id:'rwire',type:'lectura',src:'retrieval',title:'Entender tubo interior, cabeza y overshot',lang:'Inglés',learn:'Lee la descripción del sistema wireline.',note:'Artículo técnico con detalles avanzados. Empieza por la función de las piezas.',prompt:'Explica la diferencia entre el tubo interior y la sarta.',cat:1},
    {id:'rrig',type:'manual',src:'rig',title:'Reconocer un modelo: LF90D',lang:'Página en inglés · ficha en español disponible en Downloads',learn:'Observa configuración, protecciones y componentes.',note:'Ficha comercial de un modelo específico; no sustituye su manual de operación.',prompt:'¿Qué información es propia del modelo y no debes generalizar?',cat:1},
    {id:'reye',type:'lectura',src:'eye',title:'Ojos y cara: seleccionar protección',lang:'Inglés',learn:'Distingue impacto, polvo y salpicaduras.',prompt:'¿Qué peligro determina el tipo de protección?',cat:0},
    {id:'rears',type:'lectura',src:'hearing',title:'Ruido y ajuste de protectores auditivos',lang:'Inglés',learn:'Comprende ajuste, compatibilidad y uso correcto.',prompt:'¿Qué diferencia hay entre auriculares y protección auditiva?',cat:0},
    {id:'rtools',type:'lectura',src:'tools',title:'Herramientas manuales: selección y cuidado',lang:'Inglés',learn:'Reconoce defectos, entrega y almacenamiento.',prompt:'¿Qué harías con una llave desgastada?',cat:7},
    {id:'relectric',type:'lectura',src:'electric',title:'Herramientas eléctricas portátiles',lang:'Inglés',learn:'Identifica cables dañados y desconexión antes de ajustes.',note:'Estas herramientas portátiles son distintas de una perforadora minera.',prompt:'¿Quién debe reparar un equipo defectuoso?',cat:7},
    {id:'rloads',type:'lectura',src:'handling',title:'Mover cargas: más que medir el peso',lang:'Inglés',learn:'Evalúa forma, agarre, estabilidad, ruta y repetición.',prompt:'¿Qué cambia cuando la carga bloquea tu vista?',cat:7},
    {id:'rslings',type:'lectura',src:'sling',title:'Reconocer daños en eslingas textiles',lang:'Inglés',learn:'Reconoce cortes, costuras dañadas y límites de uso.',note:'Estudio para reconocer y reportar; el aparejo requiere competencia específica.',prompt:'¿Por qué no puedes reparar un daño con un nudo?',cat:7},
    {id:'rlabels',type:'lectura',src:'labels',title:'Leer una etiqueta química',lang:'Inglés',learn:'Distingue identificación, peligros y precauciones.',note:'WHMIS es canadiense; aplica el etiquetado y procedimiento del proyecto.',prompt:'¿Cómo actuarías con una etiqueta ilegible?',cat:8},
    {id:'rspills',type:'lectura',src:'spill',title:'Derrames, residuos y protección ambiental',lang:'Inglés',learn:'Comprende límites de respuesta y compatibilidad de materiales.',prompt:'¿Qué puedes comunicar antes de intervenir un derrame?',cat:8},
    {id:'rresp',type:'lectura',src:'respirator',title:'Entender por qué un respirador necesita selección',lang:'Inglés',learn:'Distingue partículas, gases y vapores.',prompt:'¿Por qué cualquier mascarilla no sirve para cualquier exposición?',cat:8},
    {id:'rem',type:'lectura',src:'emergency',title:'Prepararse para una emergencia',lang:'Inglés',learn:'Revisa alertas, comunicación, rutas y conteo.',prompt:'¿Qué necesitas preguntar en la inducción?',cat:9},
    {id:'rfire',type:'lectura',src:'fire',title:'Extintores y límites para responder a un incendio',lang:'Inglés',learn:'Reconoce cuándo alertar y evacuar.',note:'No es práctica de extinción. La respuesta necesita entrenamiento presencial.',prompt:'¿Cuándo debes abandonar el intento de combatir el fuego?',cat:9},
    {id:'rconf',type:'lectura',src:'confined',title:'Tanques y pozos: reconocer espacios confinados',lang:'Inglés',learn:'Comprende acceso restringido y atmósferas peligrosas.',prompt:'¿Por qué la ausencia de olor no valida una entrada?',cat:9},
    {id:'rrescue',type:'lectura',src:'rescue',title:'Rescate: por qué no se entra improvisadamente',lang:'Inglés',learn:'Conoce la necesidad de plan, personal competente y equipos.',prompt:'¿Qué harías si ves a una persona colapsada dentro?',cat:9},
    {id:'rheat',type:'lectura',src:'heat',title:'Calor, adaptación y pausas',lang:'Inglés',learn:'Conoce controles y aclimatización.',prompt:'¿Por qué un primer día requiere adaptación?',cat:10},
    {id:'rlight',type:'lectura',src:'lightning',title:'Tormentas eléctricas y refugios',lang:'Inglés',learn:'Reconoce alerta por truenos y preparación del refugio.',prompt:'¿Qué tarea no iniciarías si amenaza tormenta?',cat:10},
    {id:'rfat',type:'lectura',src:'fatigue',title:'Fatiga: señales y efecto sobre el trabajo',lang:'Inglés · cartel con texto',learn:'Identifica cambios de atención y reacción.',prompt:'¿Cómo comunicarías fatiga antes de conducir?',cat:10},
    {id:'ralone',type:'lectura',src:'alone',title:'Trabajo aislado y contacto programado',lang:'Inglés',learn:'Conoce alternativas de comunicación y seguimiento.',prompt:'¿Qué harías si no existe cobertura celular?',cat:10},
    {id:'rtraffic',type:'lectura',src:'traffic',title:'Puntos ciegos y maniobras de maquinaria',lang:'Inglés',learn:'Comprende rutas, radio de giro y función del señalista.',prompt:'¿El chaleco confirma que el conductor te vio?',cat:6},
    {id:'recu',type:'lectura',src:'ecuador',title:'Ecuador: normativa, formatos y guías oficiales',lang:'Español',learn:'Accede al repositorio oficial del Ministerio del Trabajo.',note:'Consulta el texto y las actualizaciones aplicables con el responsable de seguridad. Las fuentes extranjeras del juego son referencias de estudio.',prompt:'¿Qué documentos y procedimientos te explicarán en la inducción?',cat:0}
  ];
  const glossary = [
    ['Testigo / core','Muestra de roca recuperada.','p1'],
    ['Broca diamantina','Herramienta de corte que reconoces en la fotografía.','v1'],
    ['Tubo interior / inner tube','Componente que recibe el testigo en wireline.','p9'],
    ['Overshot','Dispositivo de recuperación conectado al cable.','p10'],
    ['Sarta / rod string','Conjunto de barras del sistema de perforación.','p12'],
    ['Wireline','Sistema de recuperación del tubo interior mediante cable.','p10'],
    ['Recortes / cuttings','Fragmentos generados durante el corte de la formación.','p13'],
    ['EPP / PPE','Equipo de protección personal seleccionado para la tarea.','s15'],
    ['FDS / SDS','Ficha de datos de seguridad del producto.','s8'],
    ['Aislamiento / lockout','Control de energías peligrosas que debe verificarse.','s2'],
    ['Eslinga / sling','Elemento de izaje con identificación y capacidad de uso.','h14'],
    ['Señalista / spotter','Persona formada y designada para comunicar una maniobra.','f14'],
    ['Relevo / handover','Intercambio de información entre cuadrillas o turnos.','f3'],
    ['Punto de reunión / muster point','Lugar previsto para reunirse y realizar el conteo en una evacuación.','e3'],
    ['Recuperación de testigo','Longitud recuperada dividida por avance, expresada en porcentaje.','c10'],
    ['Aclimatización','Adaptación gradual al ambiente de trabajo con calor.','r1']
  ];
  const interviews = [
    {q:'Describe cómo te imaginas un turno como ayudante.',hint:'Usa el recorrido de campo: preparación, apoyo supervisado, muestras y relevo. Aclara que las tareas concretas dependen del proyecto.',example:'«Esperaría recibir el plan, conocer los riesgos y apoyar al perforista en lo que me asignen y enseñen. Podría colaborar con herramientas, materiales y muestras, y comunicar pendientes al entregar el turno. Confirmaría mis funciones en la inducción».',checks:['Describo preparación.','Menciono apoyo supervisado.','Incluyo muestras o herramientas.','Reconozco que el proyecto define las funciones.']},
    {q:'¿Qué harías si el código de una caja no coincide con el pedido?',hint:'Explica cómo confirmarías identificadores antes de entregar. Evita inventar una corrección o cambiar muestras.',example:'«Mantendría las muestras identificadas y consultaría al responsable comparando pedido, pozo y caja. No entregaría una caja como correcta hasta resolver la discrepancia».',checks:['Detecto la discrepancia.','Verifico los campos.','Consulto al responsable.','No invento ni mezclo datos.']},
    {q:'¿Qué harías si te piden conducir y estás muy fatigado?',hint:'Describe una comunicación temprana y concreta. No prometas resolver el cansancio solo con café.',example:'«Avisaría que estoy teniendo problemas de atención y no asumiría la conducción en esas condiciones. Pediría aplicar el procedimiento de fatiga y organizar una alternativa segura».',checks:['Reconozco la fatiga.','La comunico.','Evito la tarea de riesgo.','Solicito una alternativa segura.']},
    {q:'¿Cómo reportarías una condición insegura por radio?',hint:'Practica un mensaje breve: ubicación, observación y ayuda necesaria. Usa el canal y la identificación que indique el proyecto.',example:'«Soy [identificación], en [ubicación]. Observo [condición concreta]. Estoy fuera de la exposición y solicito revisión del responsable. Confirmo recepción».',checks:['Identifico ubicación.','Describo el hecho.','No invento una causa.','Solicito respuesta y confirmación.']},
    {q:'¿Qué significa para ti ser proactivo sin experiencia?',hint:'Propón organizar, preguntar, observar y reportar dentro de lo asignado. Iniciativa no implica tocar controles o reparar sin formación.',example:'«Puedo anticipar lo que necesito para la tarea, mantener las herramientas organizadas y preguntar si no entiendo. Si observo un problema, lo reporto; para operar o intervenir equipos necesito formación y autorización».',checks:['Propongo acciones concretas.','Pregunto cuando hay dudas.','Comunico observaciones.','Reconozco límites de formación.']},
    {q:'Dime una ocasión en la que cometiste un error y lo corregiste.',hint:'Elige un caso real y pequeño. Explica cómo lo detectaste, lo comunicaste y evitaste repetirlo.',example:'«En [situación real] me equivoqué en [dato o tarea]. Lo detecté al [verificación], informé a [persona] y corregí [acción]. Después incorporé [comprobación] para reducir la repetición».',checks:['El ejemplo es real.','Reconozco mi error.','Explico corrección y comunicación.','Menciono lo que aprendí.']},
    {q:'¿Cómo actuarías ante un derrame que no sabes identificar?',hint:'Recuerda el caso del juego y el plan de respuesta. Tu aporte puede ser reconocer, alertar y evitar exposición; no improvisar una limpieza.',example:'«Me alejaría de la exposición, alertaría a las personas y al responsable según el plan, y describiría la ubicación y lo observado. No limpiaría un producto desconocido sin capacitación y equipo adecuados».',checks:['Evito exposición.','Alerto según el plan.','Describo hechos y lugar.','No improviso la limpieza.']},
    {q:'¿Qué información transmitirías al terminar el turno?',hint:'Practica distinguir realizado, pendiente y condición observada. Usa un ejemplo ficticio claramente identificado como práctica.',example:'«En un ejemplo de práctica diría: se completó el inventario asignado; queda confirmar una etiqueta, y la caja permanece identificada. Se avisó al responsable. También comunicaría cualquier condición relevante de seguridad».',checks:['Distingo ejemplo de experiencia real.','Menciono lo completado.','Indico pendientes.','Incluyo comunicación de seguridad.']}
  ];
  window.PERFO_EXPANSION = {sources,cats,bank,field,resources,glossary,interviews,reviewDate:'2026-10-01'};
})();
